Try at converting to qt6, fails to start on NetBSD:

Traceback (most recent call last):
  File "/usr/pkg/bin/thg", line 163, in <module>
    tortoisehg.hgqt.run.run()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 247, in __getattribute__
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/pkg/lib/python3.11/site-packages/tortoisehg/hgqt/run.py", line 500, in <module>
    qtrun = qtapp.QtRunner()
            ^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 247, in __getattribute__
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/pkg/lib/python3.11/site-packages/tortoisehg/hgqt/qtapp.py", line 40, in <module>
    from .qtnetwork import (
  File "/usr/pkg/lib/python3.11/site-packages/hgdemandimport/demandimportpy3.py", line 50, in exec_module
    self.loader.exec_module(module)
  File "/usr/pkg/lib/python3.11/site-packages/tortoisehg/hgqt/qtnetwork.py", line 15, in <module>
    from PyQt6.QtNetwork import *  # pytype: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 288, in create_module
ImportError: /usr/pkg/lib/python3.11/site-packages/PyQt6/QtNetwork.abi3.so: Undefined PLT symbol "_ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate" (symnum = 1588)
